import { SITE } from "@/lib/constants/site";

/** Generated by `app/opengraph-image.js`. */
const DEFAULT_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE.name}: get access to hundreds of courses`,
};

/**
 * Page metadata with consistent canonical URL, Open Graph and Twitter cards.
 * Titles use the root template ("Courses | ByteSpace").
 *
 * @param {object} options
 * @param {string} [options.title] page title (omit for the home page default)
 * @param {string} [options.description]
 * @param {string} options.path canonical path, e.g. "/courses"
 * @param {{ src: string, alt: string }} [options.image] share image (defaults to the generated OG image)
 * @param {"website" | "article" | "profile"} [options.type="website"]
 * @returns {import("next").Metadata}
 */
export function buildMetadata({
  title,
  description = SITE.description,
  path,
  image,
  type = "website",
}) {
  const images = [image ? { url: image.src, alt: image.alt } : DEFAULT_IMAGE];
  return {
    ...(title && { title }),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: SITE.name,
      locale: SITE.locale,
      title: title ?? SITE.title,
      description,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: title ?? SITE.title,
      description,
      images,
    },
  };
}
